"""MEMORY.md — lightweight context index that's always loaded.

This is the first layer of the three-layer context system.
MEMORY.md stays small (~150 chars per line) and is always included
in the prompt for cache stability.
"""

from pathlib import Path


class MemoryManager:
    """Manages the MEMORY.md context index file.

    This file is always loaded into the LLM context to provide
    a lightweight index of the project state. It's kept small
    to maintain cache stability.
    """

    def __init__(self, workspace: Path):
        self.workspace = workspace
        self._memory_file = workspace / "MEMORY.md"
        self._entries: list[str] = []

    def load(self) -> list[str]:
        """Load memory entries from MEMORY.md."""
        if self._memory_file.exists():
            content = self._memory_file.read_text(encoding="utf-8")
            self._entries = [
                line.strip() for line in content.splitlines()
                if line.strip() and not line.startswith("#")
            ]
        return self._entries

    def add_entry(self, entry: str) -> None:
        """Add a lightweight entry to the memory index."""
        if len(entry) > 200:
            entry = entry[:197] + "..."
        self._entries.append(entry)
        self._save()

    def update_entry(self, index: int, entry: str) -> None:
        """Update a specific memory entry."""
        if 0 <= index < len(self._entries):
            self._entries[index] = entry
            self._save()

    def remove_entry(self, index: int) -> None:
        """Remove a memory entry."""
        if 0 <= index < len(self._entries):
            self._entries.pop(index)
            self._save()

    def get_context_block(self) -> str:
        """Return the memory block for inclusion in the LLM prompt."""
        if not self._entries:
            return ""
        lines = ["## Project Context (MEMORY.md)", ""]
        for i, entry in enumerate(self._entries):
            lines.append(f"- {entry}")
        return "\n".join(lines)

    def clear(self) -> None:
        """Clear all memory entries."""
        self._entries.clear()
        self._save()

    def _save(self) -> None:
        """Persist memory to disk."""
        content = "# MEMORY.md — Project Context Index\n"
        content += "# Auto-generated by ZOUWUCODE\n\n"
        for entry in self._entries:
            content += f"{entry}\n"
        self._memory_file.write_text(content, encoding="utf-8")